//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxSpellChecker_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxSpellChecker_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxSpellChecker_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al Diccionario.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_AddToDictionaryButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.AddToDictionaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CancelButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar todos.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar A:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeTo {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elije el diccionario a usar para la comprobación ortográfica..
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChooseDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChooseDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CloseButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La revisión ortográfica ha finalizado..
        /// </summary>
        internal static string ASPxSpellCheckerStringId_FinishSpellChecking {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.FinishSpellChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones Generales.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_GeneralOptions {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar todo.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar e-mails.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreEmails {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar palabras con altura mixta.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreMixedCase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreMixedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar palabras con números.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreNumbers {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar una vez.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreOnceButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreOnceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar tags delimitadores.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreTags {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar palabras en MAYÚSCULA.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUppercase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignorar URLs.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUrls {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diccionarios internacionales.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_InternationalDictionaries {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.InternationalDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_Language {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Sin sugerencias).
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NoSuggestionsText {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NoSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No en Diccionario:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NotInDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OkButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones....
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones de Ortografía.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobar ortografía.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_SpellCheckFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.SpellCheckFormCaption", resourceCulture);
            }
        }
    }
}
