//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxEditors_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxEditors_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxEditors_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaciar.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Clear {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Today {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código introducido no es correcto.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen Captcha.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultImageAlternateText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultImageAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el código mostrado:.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultTextBoxLabelText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultTextBoxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar otro código.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_RefreshText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionado.
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Checked {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No seleccionado.
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Unchecked {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor inválido.
        /// </summary>
        internal static string ASPxEditorsStringId_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;lt;vacío&amp;gt;.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterConrol_Empty {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterConrol_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;lt;ingrese un valor&amp;gt;.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterConrol_EmptyEnter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterConrol_EmptyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Condición.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddCondition {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega una nueva condición a este grupo.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Grupo.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddGroup {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega un nuevo elemento a la lista.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddValueHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_BetweenAnd {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_BetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iguala,No Iguala,Es mayor que,Es mayor o Igual a,Es menor que,Es menor o igual a,Está entre,No está entre,Contiene,No contiene,Comienza con,Finaliza con,Es similiar,No es similar,Es blanco,No es blanco,Es alguno de,Es ninguno de.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClauseType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClauseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaciar.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Y,O,No Y,No O.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_GroupType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor de Filtros.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_PopupHeaderText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_PopupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Remove {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quita la condición.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_RemoveConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_RemoveConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear filtro.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ShowFilterControl {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ShowFilterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló la validación de expresión Regular.
        /// </summary>
        internal static string ASPxEditorsStringId_RegExValidationErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RegExValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *.
        /// </summary>
        internal static string ASPxEditorsStringId_RequiredFieldErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RequiredFieldErrorText", resourceCulture);
            }
        }
    }
}
