//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxScheduler_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxScheduler_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxScheduler_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        internal static string ASPxSchedulerStringId_CaptionViewNavigator_Today {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.CaptionViewNavigator_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Day {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a día(s).
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Days {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar eliminación.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_DeleteRecurrentApt {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_DeleteRecurrentApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar información de detalle.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_DetailInfo {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_DetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Error {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cada.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Every {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cada día de semana.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_EveryWeekday {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a Fecha.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_GotoDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_GotoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Info {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mes(es).
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Months {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ocurrencias.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Occurrences {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Of {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de cada.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OfEvery {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Elemento Recurrente.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OpenRecurrentApt {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OpenRecurrentApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presione ESC para cancelar la operación.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OperationToolTip {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OperationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar por:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurenceRange_EndBy {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurenceRange_EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin fecha final.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurenceRange_NoEndDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurenceRange_NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar después de:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurenceRange_OccurrenceCount {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurenceRange_OccurrenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurrir cada.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurEvery {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetición.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Recurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diariamente.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Daily {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensualmente.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Monthly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semanalmente.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Weekly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anualmente.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Yearly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar más.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_ShowMore {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El/La.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_The {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0:D} &amp;ndash; {1:D}.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_ViewVisibleInterval_Format {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_ViewVisibleInterval_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuidado.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Warning {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a semanas(s) en:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_WeeksOn {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_WeeksOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atrás.
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_Backward {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adelante.
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_Forward {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_Forward", resourceCulture);
            }
        }
    }
}
