//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Datos a Mostrar.
        /// </summary>
        internal static string ASPxperienceStringId_DataViewBase_EmptyDataText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataViewBase_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las páginas.
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerSummaryAllPages {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerSummaryAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página {0} de {1}.
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerSummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando&amp;hellip;.
        /// </summary>
        internal static string ASPxperienceStringId_Loading {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al comienzo.
        /// </summary>
        internal static string ASPxperienceStringId_NewsControl_BackToTop {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.NewsControl_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página:.
        /// </summary>
        internal static string ASPxperienceStringId_NewsControl_Page {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.NewsControl_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_All {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_First {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Last {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Next {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Prev {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Páginas: {0} - {1} ({2} elementos).
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryAllPagesFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryAllPagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página {0} of {1} ({2} elementos).
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Cerrar].
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_CloseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Redimensionar].
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_SizeGrip {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_SizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Ir al comienzo].
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_BackToTop {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro:&amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_FilterCaption {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_FilterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;b&gt;?&lt;/b&gt; = cualquier carácter único
        ///&lt;b&gt;*&lt;/b&gt; = cualquier carácter.
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_FilterHint {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos para este criterio de filtro.
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_NoData {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_AddButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_CancelButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló la subida del fichero porque el atributo enctype del formulario no está establecido como &apos;multipart/form-data&apos;.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_EnctypeError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_EnctypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero a subir no existe.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_FileDoesNotExistError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_FileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falló la subida del fichero por razones ajenas al control ASPxUploadControl.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_GeneralError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta &quot;{0}&quot; no es una ruta de Windows válida..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_InvalidWindowsPath {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_InvalidWindowsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud total del contenido de los archivos seleccionados para subir excede la longitud máxima de pedido permitida ({0} Kb) definida por la aplicación..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MaxRequestLengthExceeded {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MaxRequestLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño del fichero excede el tamaño autorizado de {0} bytes.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MaxSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éste tipo de contenido no está permitido.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_NotAllowedContentTypes {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_NotAllowedContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ésta extensión de fichero no está permitido.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_NotAllowedFileExtension {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_NotAllowedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_RemoveButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UploadButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UploadButton", resourceCulture);
            }
        }
    }
}
