//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_XtraReports_v10_1_Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_XtraReports_v10_1_Web() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_XtraReports_v10_1_Web", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Csv.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_csv {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mht.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_mht {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_mht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pdf.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_pdf {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_png {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rtf.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_rtf {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_txt {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xls.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_xls {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xlsx.
        /// </summary>
        internal static string ASPxReportsStringId_ExportName_xlsx {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ExportName_xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Cancel {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;u&gt;C&lt;/u&gt;oincidir mayúculas/minúsculas.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Case {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a c.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Case_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Case_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aba&lt;u&gt;j&lt;/u&gt;w.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Down {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a j.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Down_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Down_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Siguiente.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_FindNext {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qué&amp;nbsp;&lt;u&gt;b&lt;/u&gt;uscar.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_FindWhat {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a b.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_FindWhat_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_FindWhat_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha finalizado la búsqueda..
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Finished {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Header {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;u&gt;A&lt;/u&gt;rriba.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Up {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_Up_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_Up_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solamente &lt;u&gt;p&lt;/u&gt;alabras completas.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_WholeWord {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a p.
        /// </summary>
        internal static string ASPxReportsStringId_SearchDialog_WholeWord_AccessKey {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.SearchDialog_WholeWord_AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera Página.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_FirstPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última Página.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_LastPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Siguiente.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_NextPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_OfLabel {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_OfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PageLabel {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Anterior.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PreviousPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir la página actual.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PrintPage {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PrintPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir el informe.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_PrintReport {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar el informe y guardarlo en disco.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_SaveToDisk {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_SaveToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar el informe y abrirlo en una nueva ventana.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_SaveToWindow {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_SaveToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar la pantalla de búsqueda.
        /// </summary>
        internal static string ASPxReportsStringId_ToolBarItemText_Search {
            get {
                return ResourceManager.GetString("ASPxReportsStringId.ToolBarItemText_Search", resourceCulture);
            }
        }
    }
}
