//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxHtmlEditor_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxHtmlEditor_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxHtmlEditor_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restricciones de Proporción activadas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restricciones de Proporción desactivadas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportionsOff {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportionsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonCancel {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonChange {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonInsert {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonOk {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Imagen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Enlace.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeTableColumn_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeTableColumn_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar CSS.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandApplyCss {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandApplyCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de Fondo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBackColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negrita.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBold {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viñetas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBulletList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alinear al centro.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobar ortografía.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCheckSpelling {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCopy {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCut {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de Frente.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandForeColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sangría.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandIndent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursiva.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandItalic {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandJustify {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alinear a la izquierda.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista ordenada.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOrderedList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sangría hacia afuera.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOutdent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOutdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pegar.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPaste {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pegar desde Word.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPasteRtf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPasteRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPrint {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rehacer.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRedo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar formato.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRemoveFormat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alinear a la Derecha.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tachado.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandStrikethrough {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subíndice.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSubscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superíndice.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSuperscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subrayado.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnderline {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshacer.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUndo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar enlace.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnlink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Imagen....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Enlace....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Celdas....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableCellProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Columnas....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableColumnProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Tablas....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Filas....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableRowProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableRowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Tabla.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTable {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Columna.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTableColumn {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Fila.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTableRow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DesignViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DesignViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Fuente.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño Fuente.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HTML.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_HtmlViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.HtmlViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear miniatura.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CreateThumbnail {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño Propio.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CustomSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Description {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre de imagen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_NewImageName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_NewImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de imagen original.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_OriginalSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pixels.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Pixels {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Position {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alineado a la izquierda.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alineado a la derecha.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anchura.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar imagen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la dirección web de la imagen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_EnterUrl {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde esta computadora.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromLocal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde la web (URL).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromWeb {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más opciones.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_MoreOptions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsualizar imagen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_Preview {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar archivo en este servidor.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_SaveToServer {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_SaveToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorar su computadora para encontrar la imagen a subir.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UploadInstructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UploadInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envolver texto alrededor del imagen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UseFloat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UseFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar enlace.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de visualización.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_DisplayProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_DisplayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de E-mail.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Email {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar E-mail a.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_EmailTo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir en nueva ventana.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_OpenInNewWindow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Subject {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Text {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sugerencia.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Url {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar una Tabla.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Columna a la Izquierda.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableColumnToLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableColumnToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Columna a la Derecha.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableColumnToRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableColumnToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Fila Encima.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableRowAbove {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Fila Debajo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableRowBelow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesibilidad.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Accessibility {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alineación.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centrado.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Center {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Izquierda.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Left {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derecha.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Right {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apariencia.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Appearance {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar a todas las celdas de la tabla.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_ApplyToAllCell {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_ApplyToAllCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustar anchura a contenidos.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_AutoFitToContent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_AutoFitToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color del fondo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BgColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color borde.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BorderColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño borde.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BorderSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambos.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Both {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Caption {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relleno de celdas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_CellPaddings {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_CellPaddings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espaciado de celdas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_CellSpacing {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_CellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Columns {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Custom {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igualar anchuras de columnas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_EqualColumnWidths {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_EqualColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera Columna.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FirstColumn {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera Fila.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FirstRow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anchura Total.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FullWidth {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabeceras.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Headers {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_HorzAlignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_HorzAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Layout {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguno.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_None {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Rows {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de la Tabla.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumario.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Summary {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inferior.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Bottom {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Middle {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superior.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Top {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vertical.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VertAlignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VertAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anchura.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusionar Abajo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_MergeTableCellDown {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.MergeTableCellDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusionar a la Derecha.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_MergeTableCellHorizontal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.MergeTableCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Paragraph {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor pegue dentro del siguiente cuadro y presione OK..
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_Instructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia de Fuente Strip.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_StripFont {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista previa.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PreviewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PreviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es requerido.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_RequiredFieldError {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Todo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectAll {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partir Horizontalmente.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SplitTableCellHorizontal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SplitTableCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partir Verticalmente.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SplitTableCellVertical {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SplitTableCellVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Celdas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableCellProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Columnas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableColumnProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Tablas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Filas.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableRowProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableRowProperties", resourceCulture);
            }
        }
    }
}
