//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxPivotGrid_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxPivotGrid_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxPivotGrid_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Contraer].
        /// </summary>
        internal static string PivotGridStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar.
        /// </summary>
        internal static string PivotGridStringId_Alt_DragHideField {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_DragHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Expandir].
        /// </summary>
        internal static string PivotGridStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Filtrar].
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterButton {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Filtrado].
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterButtonActive {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Redimensionar].
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterWindowSizeGrip {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterWindowSizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Ascendente).
        /// </summary>
        internal static string PivotGridStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Descendente).
        /// </summary>
        internal static string PivotGridStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este comando no puede ser usado con selecciones múltiples..
        /// </summary>
        internal static string PivotGridStringId_CannotCopyMultipleSelections {
            get {
                return ResourceManager.GetString("PivotGridStringId.CannotCopyMultipleSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string PivotGridStringId_CellError {
            get {
                return ResourceManager.GetString("PivotGridStringId.CellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área de Columnas.
        /// </summary>
        internal static string PivotGridStringId_ColumnArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.ColumnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelte Campos de Columna Aquí.
        /// </summary>
        internal static string PivotGridStringId_ColumnHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.ColumnHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar a.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormAddTo {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solamente Secciones de Áreas (1 por 4).
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormBottomPanelOnly1by4 {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormBottomPanelOnly1by4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solamente Secciones de Áreas (2 por 2).
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormBottomPanelOnly2by2 {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormBottomPanelOnly2by2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de campos del PivotGrid.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización de Diseño Diferido.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormDeferLayoutUpdate {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormDeferLayoutUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre los campos entre las áreas mostradas:.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormHint {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalla de Personalizaciones del Diseño.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormLayoutButtonTooltip {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormLayoutButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre un campo aquí para personalizar el diseño.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormListBoxText {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormListBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secciones de Campos y Áreas Apiladas.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormStackedDefault {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormStackedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secciones de Campos y Áreas Uno-a-lado-de-otro.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormStackedSideBySide {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormStackedSideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre Elementos al Cubo.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormText {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solamente Sección de Campos.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormTopPanelOnly {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormTopPanelOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormUpdate {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área de Datos.
        /// </summary>
        internal static string PivotGridStringId_DataArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        internal static string PivotGridStringId_DataFieldCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataFieldCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelte Elementos de Datos Aquí.
        /// </summary>
        internal static string PivotGridStringId_DataHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Prefiltro.
        /// </summary>
        internal static string PivotGridStringId_EditPrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.EditPrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área de Filtro.
        /// </summary>
        internal static string PivotGridStringId_FilterArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string PivotGridStringId_FilterCancel {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelte Campos de Filtro Aquí.
        /// </summary>
        internal static string PivotGridStringId_FilterHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Ocultar Todos).
        /// </summary>
        internal static string PivotGridStringId_FilterHideAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterHideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Ocultar Vacíos).
        /// </summary>
        internal static string PivotGridStringId_FilterHideBlanks {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterHideBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invertir Filtro.
        /// </summary>
        internal static string PivotGridStringId_FilterInvert {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string PivotGridStringId_FilterOk {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Mostrar Todos).
        /// </summary>
        internal static string PivotGridStringId_FilterShowAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Mostrar Vacíos).
        /// </summary>
        internal static string PivotGridStringId_FilterShowBlanks {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterShowBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Filtro.
        /// </summary>
        internal static string PivotGridStringId_FilterType {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar valores seleccionados.
        /// </summary>
        internal static string PivotGridStringId_FilterTypeExcluded {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterTypeExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar valores seleccionados.
        /// </summary>
        internal static string PivotGridStringId_FilterTypeIncluded {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterTypeIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total General.
        /// </summary>
        internal static string PivotGridStringId_GrandTotal {
            get {
                return ResourceManager.GetString("PivotGridStringId.GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comando de Mostrar Detalles no se puede ejecutar cuando existen múltiples campos seleccionados en el filtro del informe. Seleccione un solo elemento por campo en el informe antes de intentar profundizar en los datos..
        /// </summary>
        internal static string PivotGridStringId_OLAPDrillDownFilterException {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPDrillDownFilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medidas.
        /// </summary>
        internal static string PivotGridStringId_OLAPMeasuresCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPMeasuresCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar Ordenación.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuClearSorting {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuCollapse {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer Todos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuCollapseAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuExpand {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir Todos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuExpandAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuFieldOrder {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuFieldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHideField {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Lista de Campos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHideFieldList {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHideFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Prefiltro.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHidePrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHidePrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover al Principio.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoBeginning {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover al Final.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoEnd {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover a la Izquierda.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoLeft {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover a la Derecha.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoRight {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refrescar Datos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuRefreshData {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuRefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar Ordenación.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuRemoveAllSortByColumn {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuRemoveAllSortByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor de Expresiones....
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowExpression {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Lista de Campos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowFieldList {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Prefiltro.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowPrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowPrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar A-Z.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortAscending {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar Z-A.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortDescending {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar &quot;{0}&quot; por Ésta Columna.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortFieldByColumn {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortFieldByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar &quot;{0}&quot; por Ésta Fila.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortFieldByRow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortFieldByRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prefiltro del PivotGrid.
        /// </summary>
        internal static string PivotGridStringId_PrefilterFormCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrefilterFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseñador de Impresión.
        /// </summary>
        internal static string PivotGridStringId_PrintDesigner {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predeterminado.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryDefault {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores de Campos.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabeceras.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líneas.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezados de Columna.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerColumnHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezados de Datos.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerDataHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerDataHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De Filtros.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerFilterHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerFilterHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabeceras en Cada Página.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerHeadersOnEveryPage {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerHeadersOnEveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líneas Horiz.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerHorizontalLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerHorizontalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusionar Valores Columnas.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerMergeColumnFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerMergeColumnFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusionar Valores de Filas.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerMergeRowFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerMergeRowFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comportamiento.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerPageBehavior {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerPageBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerPageOptions {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerPageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezados de fila.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerRowHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerRowHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos de Filtro sin uso.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerUnusedFilterFields {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerUnusedFilterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar Apariencia Impresión.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerUsePrintAppearance {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerUsePrintAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líneas verticales.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerVerticalLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerVerticalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área de Filas.
        /// </summary>
        internal static string PivotGridStringId_RowArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.RowArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelte Campos de Fila Aquí.
        /// </summary>
        internal static string PivotGridStringId_RowHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.RowHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrecto.
        /// </summary>
        internal static string PivotGridStringId_StatusBad {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correcto.
        /// </summary>
        internal static string PivotGridStringId_StatusGood {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutro.
        /// </summary>
        internal static string PivotGridStringId_StatusNeutral {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promedio.
        /// </summary>
        internal static string PivotGridStringId_SummaryAverage {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuento.
        /// </summary>
        internal static string PivotGridStringId_SummaryCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string PivotGridStringId_SummaryCustom {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máx.
        /// </summary>
        internal static string PivotGridStringId_SummaryMax {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mín.
        /// </summary>
        internal static string PivotGridStringId_SummaryMin {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DesvEst.
        /// </summary>
        internal static string PivotGridStringId_SummaryStdDev {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DesvEstp.
        /// </summary>
        internal static string PivotGridStringId_SummaryStdDevp {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryStdDevp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suma.
        /// </summary>
        internal static string PivotGridStringId_SummarySum {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Var.
        /// </summary>
        internal static string PivotGridStringId_SummaryVar {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Varp.
        /// </summary>
        internal static string PivotGridStringId_SummaryVarp {
            get {
                return ResourceManager.GetString("PivotGridStringId.SummaryVarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros.
        /// </summary>
        internal static string PivotGridStringId_TopValueOthersRow {
            get {
                return ResourceManager.GetString("PivotGridStringId.TopValueOthersRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string PivotGridStringId_Total {
            get {
                return ResourceManager.GetString("PivotGridStringId.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Total.
        /// </summary>
        internal static string PivotGridStringId_TotalFormat {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Promedio.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatAverage {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Cuenta.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Personalizado.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatCustom {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Máx.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatMax {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Mín.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatMin {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} DesvStd.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatStdDev {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} DesvPStd.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatStdDevp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatStdDevp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Suma.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatSum {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Varianza.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatVar {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} VarianzaP.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatVarp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatVarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descendiendo.
        /// </summary>
        internal static string PivotGridStringId_TrendGoingDown {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendGoingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subiendo.
        /// </summary>
        internal static string PivotGridStringId_TrendGoingUp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendGoingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Cambios.
        /// </summary>
        internal static string PivotGridStringId_TrendNoChange {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendNoChange", resourceCulture);
            }
        }
    }
}
