//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxTreeList_v10_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxTreeList_v10_1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxTreeList_v10_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Contraer].
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Expandir].
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Ascendente).
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Descendente).
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar eliminación.
        /// </summary>
        internal static string ASPxTreeListStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selector de Campos.
        /// </summary>
        internal static string ASPxTreeListStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nodo tiene nodos descendientes..
        /// </summary>
        internal static string ASPxTreeListStringId_RecursiveDeleteError {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.RecursiveDeleteError", resourceCulture);
            }
        }
    }
}
